export enum Endpoints {
    Branches = 'branches',
    SignIn = 'auth/signIn',
    Gallery = 'foto',
    News = 'news',
    Products = 'products',
    ProductsByCategory = 'products/by-category/',
    SubCategoryMain = 'sub-category/main',
    SubCategoryByParentId = 'sub-category/by-parent/',
    Upload = 'upload/',
    Users = 'user',
    Graphic = 'graphic',
    Get1CUserByTabNumber = 'user/find-user-with-tab-number',
    SelectbleWorkshops = 'workshop/selectable-workshop',
    SelectbleWorkshopEmployes = 'workshop/employees',
    Workshop = 'workshop',
}
