export enum Endpoints {
    Branches = 'branches',
    SignIn = 'auth/login',
    GetMe = 'auth/me',
    News = 'news',
    Upload = 'upload/',
    Users = 'user',
    Graphic = 'graphic',
    Get1CUserByTabNumber = 'user/find-user-with-tab-number',
    SelectbleWorkshops = 'workshop/selectable-workshop',
    SelectbleWorkshopEmployes = 'workshop/employees',
    Workshop = 'workshop',
    WorkShopBranches = 'workshop-branches',
    WorkShopBranchesByRefKey = 'workshop/selectable-workshop-branches/',
    Magazine = 'magazines',
    SignatureMagazine = 'magazines/signature',
    User = 'user',
}
